### ISSUE TITLE
Bubble touch not working properly

### ISSUE THREAD

**Issue by Maeil456** [TorryDo/Floating-Bubble-View#40]
### Steps to reproduce

I created a bubble using your ViewHelper, but when I touched it to expand it,There's only closebubble and it didn't expand. 

### Expected behavior

The bubble should expand when touched.

### Actual behavior

Touching the bubble didn't expand it.
With the bubble touching the edge, press the bubble toward the edge to operate.

### Floating-Bubble-View version

0.5.6

### Android version

android13

### Device

Galaxy 22+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the library to the latest **[Version](https://github.com/torrydo/Floating-Bubble-View/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by TorryDo** [comment]
hi @Maeil456, 👋

Are you experiencing the problem similar to the one shown in the video below? (sometimes it work corrrectly, sometime not).
I've noticed this issue occuriring on some devices, and I'll try to fix it ASAP.

Thank you 💖

### Android version
Android 10

### Device
Huawei matepad 10.4

https://github.com/TorryDo/Floating-Bubble-View/assets/85553681/6f7c7446-8576-48cb-9189-ad0922e1abd2

**Comment by Maeil456** [comment]
My problem similar with that video!

and also attach my video! Thx :-)

https://youtube.com/shorts/H-hoF8svoTg?si=Y5wMUj2mBbIdtEk2

2023년 9월 1일 (금) 오후 5:26, Tri Do ***@***.***>님이 작성:

**Comment by Kumpello** [comment]
Hardcoding forceDragging to false in FloatingBubble.kt solves this issue, it seems that setOnTouchListener must be used

**Comment by TorryDo** [comment]
Thank you @Kumpello 💖

Yes, set bubble `forceDragging` to false does fix this issue. However, it also reduce/ignore draggable area if the view/compose uses `.setOnClickListener{...}`/ `clickable{...}`. For example If you use use `.setOnClickListener`/`clickable` for the entire view like in the image below, you won't be able to drag it. 

![image](https://github.com/TorryDo/Floating-Bubble-View/assets/85553681/4ef08a1d-ddff-49f1-8542-e2501eaf94c0)

I'll try to fix it ASAP. Thanks

**Comment by Kumpello** [comment]
I changed onClickListener to doOnTouchEvent function but without ignoreChildEvent, it seems to fix it. What for ignoreChildEvent is needed anyway?

**Comment by TorryDo** [comment]
@Kumpello👋 If you use use `.setOnClickListener{}`/`.clickable{}` for the entire view like in the image above, you won't be able to drag it without `ingoreChildEvent`

**Comment by TorryDo** [comment]
@Kumpello 👋 when you drag the bubble, the `.onCLick`/`.clickable` won't be ignore even if you drag the view


https://github.com/TorryDo/Floating-Bubble-View/assets/85553681/b005a716-8d0f-4426-97b9-b25aea05db11

**Comment by Kumpello** [comment]
> @Kumpello 👋 when you drag the bubble, the `.onCLick`/`.clickable` won't be ignore without ignoreChildEvent
> ignore_child_ev.mp4

Thank's for answer, i worked out solution in new commit

**Comment by TorryDo** [comment]
Hi @Maeil456 👋,

This bug has been fixed in `v0.6.3`, thanks to the help of @Kumpello.

If you have any problems, don't hesitate to re-open the issue.

Thank you.

**Comment by Boguslawa-Tlolka** [comment]
Hi @TorryDo,

I still have this problem on my Samsung Galaxy S8 device with Android 9. 

I tried using 0.6.3 and 0.6.4 version of your library, but it's still not working. I also downloaded zip file with 0.6.3 and tried the sample app - it has the same issue. 

But then I manually added the fix from @Kumpello pull request and it's working fine.

Can you please verify your solution to this issue?

**Comment by TorryDo** [comment]
Hi @Boguslawa-Tlolka, I've tested on my devices (android 9 (avd), 10, 12. Both phone and tablet) and it run fine. Can you provides some videos about your cases?
Thanks.

**Comment by Boguslawa-Tlolka** [comment]
https://github.com/TorryDo/Floating-Bubble-View/assets/79993467/51093257-8677-4739-b0cc-5b96e332399e

**Comment by TorryDo** [comment]
Hey @Boguslawa-Tlolka 👋, can you try [this branch](https://github.com/TorryDo/Floating-Bubble-View/tree/bugfix/bubble-touch) and share you feedback?

**Comment by Boguslawa-Tlolka** [comment]
I think that it's better than it was, but it still has this issue
I also think that on emulator the click is too precise, so this problem doesn't happen there

https://github.com/TorryDo/Floating-Bubble-View/assets/79993467/3ae4cfc6-faf1-4067-b015-690ab37b2e74

**Comment by TorryDo** [comment]
@Boguslawa-Tlolka Did you move your finger a little after you touched the bubble? because if the bubble is moved then it's correct behavior. Anyway I think I'll provide an API to fix this issue. thanks.

**Comment by Boguslawa-Tlolka** [comment]
@TorryDo I tried not to move my finger after touching bubble and it works fine

**Comment by TorryDo** [comment]
@Boguslawa-Tlolka great!, also, does keeping your finger not moving when clicking the bubble fix the issue in [the first video you sent](https://github.com/TorryDo/Floating-Bubble-View/issues/40#issuecomment-1916935516)?. I mean if you're easily click the bubble then there is no need to fix this issue

**Comment by TorryDo** [comment]
@Boguslawa-Tlolka Can you try [this branch](https://github.com/TorryDo/Floating-Bubble-View/tree/bugfix/bubble-touch) and share your feedback again? seems like the issue is gone now

**Comment by Boguslawa-Tlolka** [comment]
@TorryDo I tried this branch and it's working fine

**Comment by dofire** [comment]
This issue has been resolved in [v0.6.5](https://github.com/TorryDo/Floating-Bubble-View/releases/tag/0.6.5). If you guys have any problems, don't hesitate to re-open the issue. Thanks ❤️
